# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./incl/AStr.h \
	./incl/InputData.h \
	./incl/NStr.h \
	./incl/OutputData.h \
	./incl/Trace.h \
	./incl/XStr.h

SOURCES += ./srce/AStr.cpp \
	./srce/InputData.cpp \
	./srce/NStr.cpp \
	./srce/OutputData.cpp \
	./srce/Trace.cpp \
	./srce/XStr.cpp

